### ISSUE TITLE
Notification icon

### ISSUE THREAD

**Issue by raspdealer** [cxii-dev/script.tvshowtime#16]
Since I've installed this plugin, all my Kodi notifications have the TvShow Time icon...

**Comment by cxii-dev** [comment]
I will check that

**Comment by cxii-dev** [comment]
I searched, and I think that it's a bug in kodi
Because I use as many others xbmcgui.Dialog().notification(heading, message[, icon, time, sound])
And the others (I have tested) have the same problem ...

**Comment by raspdealer** [comment]
Thanks for your time. Where can I post bug to Kodi ?

**Comment by cxii-dev** [comment]
http://forum.kodi.tv/
