### ISSUE TITLE
Can't sync

### ISSUE THREAD

**Issue by raspdealer** [cxii-dev/script.tvshowtime#2]
Hi,

I've installed this extension but after watch an episode on kodi, it's not mark as watched on TVShow Time...
Why ?

**Comment by cxii-dev** [comment]
Hi, you can see what does not work by activating the debug mode. After that, go to the log in .kodi / temp / kodi.log
I can help or change if mistake

I use it on 2 kodi, and there is for the moment only a few users, so if you can help ... thanks a lot

**Comment by raspdealer** [comment]
Just got this : 

18:48:47 T:2617242688  NOTICE: Closing stream player 3
18:48:47 T:2617242688   DEBUG: CSMBFile::Close closing fd 10000
18:48:47 T:2617242688   DEBUG: OMXClock::OMXStop
18:48:47 T:2617242688   DEBUG: COMXCoreComponent::Deinitialize : OMX.broadcom.clock handle 0x9aea7a48
18:48:47 T:2617242688   DEBUG: OnPlayBackStopped: play state was 2, starting 0
18:48:47 T:2617242688   DEBUG: CAnnouncementManager - Announcement: OnStop from xbmc
18:48:47 T:2617242688   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnStop
18:48:47 T:3038851072  NOTICE: DVDPlayer: finished waiting
18:48:47 T:2617242688   DEBUG: Thread DVDPlayer 2617242688 terminating
18:48:47 T:3038851072   DEBUG: CMMALRenderer::UnInit
18:48:47 T:2804679744   DEBUG: ### [TVShow Time] - onPlayBackStopped
18:48:47 T:2804679744   DEBUG: ### [TVShow Time] - onPlayBackEnded

And nothing is sync...
Is it possible to add a toaster notification on login error and on submission success ?
Thanks

**Comment by cxii-dev** [comment]
Ok, here, I don't see the 'VideoLibrary.OnUpdate' 
Are you sure that you saw the episode entirely?
The notification is when you reach the end of the episode.

**Comment by raspdealer** [comment]
Notification : Erreur de jeton veuillez reessayer

**Comment by cxii-dev** [comment]
Le jeton est obtenu apres authentification sur les serveurs de TVShow Time
Veuillez vérifier votre nom d'utilisateur et votre mot de passe
Bien à vous

**Comment by raspdealer** [comment]
Nom d'utilisateur : Il s'agit bien de l'email ?

**Comment by cxii-dev** [comment]
Votre nom d'utilisateur peut être retrouvé dans la section profile du site tvshowtime.com
Si vous êtes connecté, il y aura une notification: "Bienvenue xx"
Si vous ne l'êtes pas, c'est erreur de jeton (token)

**Comment by raspdealer** [comment]
Super! 
A présent ça fonctionne un redémarrage était nécessaire pour que l'addon et les notifications fonctionnent.
Merci !
Des updates sont prévues ?

**Comment by cxii-dev** [comment]
Super
Pour l'instant ça synchronise quand on regarde un épisode en entier et quand on demande de marquer comme lu/non lu depuis le menu contextuel de l'épisode
Je fais des tests pour que l'on puisse marquer une saison entière, mais il faut que je voie si faisable par rapport a la limitation de l'api
Sinon ça sera a peut près tout (toutes les fonctions de l'api étant utilisées)
Si vous avez une suggestion, n'hésitez pas
