### ISSUE TITLE
Version 15

### ISSUE THREAD

**Issue by raspdealer** [cxii-dev/script.tvshowtime#21]
Can you please push the last changes in a 1.0.15 please ?
Do you have news about the repo push ?
Thanks

**Comment by cxii-dev** [comment]
Hi, the 1.0.14 is already in kodi repo

**Comment by raspdealer** [comment]
http://addons.xbmc.org/show/script.tvshowtime/ still on 1.0.6

**Comment by raspdealer** [comment]
Can you please reopen this issue.

**Comment by cxii-dev** [comment]
On the web list, it's 1.0.6, but on kodi, it's 1.0.14 ...
Don't know why the web version is different ...

**Comment by raspdealer** [comment]
Is the 1.0.15 version pushed now ? 
On Kodi website, is it automatic or manual ?

**Comment by cxii-dev** [comment]
The 1.0.15 will be pushed (for Helix & Isengard)by the end of the week (doing some tests)
The website is manual I think because, it's always the 1.0.6 on it, but on kodi platform it's 1.0.14 ... I will ask the forum ...
