### ISSUE TITLE
Synchronizing from Kodi to TVShow Time – Sleep 60 secs.

### ISSUE THREAD

**Issue by khalidl** [cxii-dev/script.tvshowtime#23]
Heya!

Upon synchronizing for the first time from *Kodi* back to *TVShow Time*, and selecting **whole seasons** (or just one season or even a couple of episodes), it’ll process a couple of episodes at a time then sleep/idle for 60 seconds before proceeding. Is this an API limit?

This way it takes too long to synchronize on the first run, especially if you have a lot of shows/seasons.

**Comment by cxii-dev** [comment]
Hi, due to 10 api requests per minute limit, the script have to wait 60 seconds every 10 episodes ...
I cannot do an other way ...

**Comment by khalidl** [comment]
That's fair enough. Thanks for clearing things up.
