### ISSUE TITLE
Hide scrobbling notification

### ISSUE THREAD

**Issue by raspdealer** [cxii-dev/script.tvshowtime#25]
Start watching notifications arent hide when "show notification" is unchecked.

**Comment by raspdealer** [comment]
Can you create some specifics options like Trakt.tv add on ?
Show notification true/false
Hide notification during play true/false
Show scrobbling notification true/false

**Comment by raspdealer** [comment]
Is ti possible to move forward with this issue ? :)

**Comment by cxii-dev** [comment]
Hi, I don't really see what you want ... sorry, can you explain it ?

Thanks

**Comment by raspdealer** [comment]
I would like settings to customize notification, not just on/off. Like on TraktTV Addon.
Show notification true/false  => global on/off setting. 
Hide notification during play true/false => Sometimes TVShow time connect while i'm playing a file... A condition to show a notification would be the play status.
Show scrobbling notification true/false => I would like to hide this specific type of notification but not all notifications.

Thanks a lot :)

**Comment by cxii-dev** [comment]
Hi,

Is scrobbling mean watched ? (This is that part I do not understand very well)
I googled it and I found that scrobbling (a song) is adding it to your library

Thanks

**Comment by raspdealer** [comment]
Srobbling means to push information about what your are watching/listening (when you do it)
It's the Share & social feature on TVShowTime.

An option to hide "You are watching xxx" during the movie without hiding ALL notification.
You should take a long with trakt.tv addons option, its really nice.

https://youtu.be/m0FuEtX7C60?t=1m22s
http://www.thelinuxrain.com/content/01-articles/81-multimedia-tip-sync-your-xbmc-kodi-watched-list-with-trakt-tv/xbmctrakt3.jpg

**Comment by cxii-dev** [comment]
1.0.16 is out

**Comment by raspdealer** [comment]
There is stil 1.0.14 on official repo. Where can I download 16 package ?
Thx

**Comment by cxii-dev** [comment]
I have pulled to the official repo just now the 1.0.17
You can get it here before update: https://github.com/cxii-dev/script.tvshowtime/archive/master.zip

**Comment by raspdealer** [comment]
Worked. Thanks.
