### ISSUE TITLE
Synchro KO dans le sens KODI vers TVSHOW TIME

### ISSUE THREAD

**Issue by jofrenchy** [cxii-dev/script.tvshowtime#26]
Bonjour,

Je rencontre un problème avec l'addon Kodi (OSMC) TVSOW TIME.
La synchro fonctionne que dans un sens (TVSHOW Time vers KODI).
Dans le sens KODI vers TVSHOW TIME, cela ne fonctionne pas, KODI affiche "ERREUR SCRIPT".

Merci d'avance.

**Comment by jofrenchy** [comment]
Sans rien changer,  ça fonctionne maintenant mais pas quand on fait tout d'un coup.

**Comment by cxii-dev** [comment]
Bonjour,

Il faut peut-être préciser qu'il y a une limite de requêtes dans le temps fixée par TVShow Time ... 
Donc tout en même temps ne peut fonctionner ...

Bien à vous

**Comment by jofrenchy** [comment]
Bonjour, 
L’échec était instantané (erreur script), après si c'est pas possible il faudrait alors retirer cette option du plugin .)
Merci
