### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by ridsss** [cxii-dev/script.tvshowtime#28]
Hi, I have profiles enabled on kodi but as TVShow Time seems to load on startup before even logging into them I am getting shows marked as watched through other users profiles on kodi which I do not want. Is there any way to stop this happening? I have disabled the addon in the other profiles - which makes kodi hang & crash every time but still shows me a notification that a show has been watched through another profile. Any help would be great, thanks

**Comment by cxii-dev** [comment]
The 1.0.18 will be pulled to the official repo next month
You can get it here before update: https://github.com/cxii-dev/script.tvshowtime/archive/master.zip
