### ISSUE TITLE
Sync from TVShow Time

### ISSUE THREAD

**Issue by Rian83** [cxii-dev/script.tvshowtime#4]
Bonjour,

Je suis au courant de la limitation de l'API à 10 requêtes, mais est-il possible de faire la synchro dans le sens API -> Kodi.
Il faudrait juste faire tourner le process 10 fois / minutes pendant X minutes (selon la taille de la biblio).

Et est-il possible, lorsque on se rend dans une saison, de faire un check de l'api pour vérifier que le statut est bien à jour ? Cela permettrai de cocher "watched" depuis son smartphone via l'appli TVShow Time et Kodi mettrai juste le dossier dans lequel on est à jour (tout en respectant 10 requêtes par minute).

Thanks

PS : I noticed that you speak french. If I'm wrong, ask me I'll switch to english back

**Comment by cxii-dev** [comment]
Bonjour,

Je peux regarder si c'est faisable. Mais de ce que je sais, c'est qu'il y a un processus après avoir marqué comme lu une série, mais pas pour une saison ...
Pour ce qui est de marquer un épisode comme vu depuis kodi ou smartphone, ça fonctionne déjà.

Bien à vous

**Comment by Rian83** [comment]
Bonjour,

Ce que je disais avec son smartphone, c'est que depuis l'appli TVShow Time, j'aimerais marqué mon épisode comme vu, et que cela se répercute sur ma biblio kodi. Aujourd'hui ce n'est pas le cas car l'add-on ne fait "que" marquer les épisodes vu via kodi directement (ce qui est déjà très bien).

Et donc au final, ca revient a créer un synchro a double sens, à savoir dès qu'on browse un dossier, que le script aille récupérer le statut de chaque épisode qui s'y trouve. Quitte a ce que le script tourne 20min en backgroud c'est pas grave (ce qui n'est pas cense arriver aussi longtemps car y a peu d'épisode dans une saison et qu'on met rarement tous les épisodes à la racine)

-- 
Florian L.

**Comment by raspdealer** [comment]
Cette proposition prend du sens si l'épisode est lu avec un autre "outil" que Kodi... 
Ça rejoins ma proposition de faire de ce plugin un "Programme" et non "Service" sous Kodi afin de pouvoir le lancer manuellement pour forcer une synchronisation manuelle API>KODI.

**Comment by Rian83** [comment]
Ce qui est en effet le cas :) j'ai déjà une TV smart qui intègre un client upnp, ainsi je lis mes videos depuis upnp (qui ici ne gère bien entendu pas le marquage des épisodes, donc j'utilise directement l'appli de tvshow time).

Et quand je retourne sur ma petite tv ancienne qui a kodi de connecté, et bien dans l'idéal il faudrait que les episodes puissent se marquer en lue grâce à l'api.

En revanche je ne connais pas la subtilité de programme et service sur kodi.

-- 
Florian L.

**Comment by raspdealer** [comment]
Quand le plugin est crée / développé, il peut être de type Service comme actuellement, ce qui signifie qu'il sera en tâche de fond uniquement (Lancé par des évènements)

Il peut également être de type Programme, comme celui de trakt.tv (concurrent international Séries et Film de tvshowtime). Il s’exécute également en fond mais peut aussi être lancé manuellement comme un programme. Dans le cas de l'exemple de trakt.tv, il lance une synchronisation complète.

**Comment by cxii-dev** [comment]
Bonjour,

je suis en train de développer une version avec un cron ...
mais j'ai perdu un peu de temps avec le retour en arrière de l'authentification de l'api

**Comment by cxii-dev** [comment]
Bonjour,
Malheureusement, c'est un peu tordu par les cheveux ...
J'ai en fait, 850 episodes dans ma library, si je prend 10 vérifications par minutes, ce qui fait au mieux 85 minutes, donc 1 heure 25. Pendant ce temp, le lecteur est bloqué par la boucle. Si je fait 2 vérifs par jour, ça veut dire 3 heures ou je ne peut pas utiliser le kodi ...
Si je coupe pendant que je lis, je vais vérifier plusieurs fois les premiers fichiers de ma biblio ... 
Ce qui vaut dire aussi je que vais au mieux faire 1700 requetes par jour, plus mes lectures ... (51000 par mois) ça fait beaucoup.
J'ai quand même fait le travail: https://github.com/cxii-dev/script.tvshowtime-crazy (mais je ne le mettrai pas sur la repo kodi 
Bien à vous

**Comment by Rian83** [comment]
Bonjour,

Je pense sinon qu'on peut trouver des alternatives de fonctionnement.
Est-il possible d'ajouter un élément dans le menu contextuel ? Si oui, on pourrait ajouter un bouton "Sync with TVShowTime".

Mais sinon, merci de l'update, je test ca en rentrant

-- 
Florian L.

**Comment by raspdealer** [comment]
Rian83, c'est une excellente idée mais elle rejoint mon point => Il faudrait que l'add-on soit un programme et non un service. Comme ça, il suffirait de le lancer dans Kodi (Menu Programmes) pour que la synchronisation se lance toute seule. Pas besoin de rajouter un menu contextuel.

Cependant cela ne règle pas le problème qu'elle peut durer très longtemps...

**Comment by Rian83** [comment]
Le problème d'aller dans l'app et de la lancer, c'est que c'est pas user friendly, a savoir il faut sortir du menu des series et aller dans l'add-on pour le lancer.
Ainsi, cela implique aussi une FULL synchro.

Si en revanche on le fait sur un dossier bien particulier on évite ces 2 problèmes:
- pas besoin d'aller dans le menu de l'app
- on cible ou doit se faire la synchro donc on limite le nombre de fichier donc c'est ultra rapide

-- 
Florian L.

**Comment by cxii-dev** [comment]
Bonjour,

J'ai ajouté à la version 13 un mini programme permettant de synchroniser tout ou une partie de la librairie
La prochaine étape est de trouver le moyen de rajouter ça au "sous menu" dans le ui des fichiers

**Comment by cxii-dev** [comment]
Damned: http://forum.kodi.tv/showthread.php?tid=216502

**Comment by Rian83** [comment]
Too bad :( 
Un jour ca viendra peut être. 

En attendant, pour limite le sync a un dossier, on pourrait aller dans le menu de l'addon (car on a ps le choix pour le moment) et quand on lance l'add on, on nous propose soit une full sync, soit la deuxieme option et dans ce cas un explorateur de bibliothèque apparait pour qu'on choisisse le dossier.

-- 
Florian L.

**Comment by cxii-dev** [comment]
Dans la version 13, j'ai ajouté ça au niveau du plugin (programme), on peut choisir le sens, toute la librairie, une série ou une saison ...
Dans la version 14, j'ai rajouté le menu "lancer"/"launch" et le nouveau système d'authentification

**Comment by raspdealer** [comment]
Le plugin est donc maintenant un programme et plus un service ?
Est-ce que le changement se fait automatiquement dans Kodi ?
Le sens signifie ? Kodi > TST ou TST > Kodi ?

**Comment by cxii-dev** [comment]
Le plugin est un service qui met a jour à la lecture et avec le sous-menu d'un épisode 'watched' / 'unwatched'
Et un programme qui permet de mettre à jour via le 'launch' dans les 2 sens (tvshowtime vers kodi et kodi vers tvshowtime) que se soit pour l'entière librairie, une série ou une saison

**Comment by gilbert1995** [comment]
Question: pourquoi ne pas essayer d'expliquer la situation au créateur de TVShowTime pour qu'il t'autorise plus de 10/requêtes par minutes?

**Comment by cxii-dev** [comment]
Ils m'avaient augmenté à 100 pour les tests mais veulent rester à 10 pour le live ...
