### ISSUE TITLE
Make script work when streaming

### ISSUE THREAD

**Issue by JoseFSilva** [cxii-dev/script.tvshowtime#44]
It would be a nice feature for this script to work when streaming an episode. Example: by torrent with Quasar/Torrenter.
Such a feature would eradicate the need for downloading the episode completely, and have TVShow Time library updated (episode marked as watched).

**Comment by JoseFSilva** [comment]
@cxii-dev If this is feasible I could develop this feature myself. Could you please give me some guidelines on how to achieve this?

**Comment by cxii-dev** [comment]
Hello, I could check if it's possible. I will try to find out how to stream an episode on my laptop to find a way to catch the name of the show and the season/episode numbers. I keep you in touch.
Cheers

**Comment by cxii-dev** [comment]
Please try the 1.1.1
Cheers

**Comment by JoseFSilva** [comment]
Thank you for getting back at me so promptly.

I tested with 4 torrents and different torrent streaming addons and only one didn't work because there was a link before the filename string, like so: [www.stupidlink.com].The.Tv.Show.Name.S01.E01. But I suppose that's the uploader's fault and not the script.

The remaining torrents were detected correctly.

**Comment by JoseFSilva** [comment]
Also, coming from 1.0.8, I noticed you added more notification settings and they are more than welcome! :)
Cheers

**Comment by cxii-dev** [comment]
Hi,
Thank's 4 your return
The problem here is that I only get the playing file and not the show, the season and the episode from the kodi player.
Maybe 2 solutions: 1. add tvshowtime to quasar like trakt - 2. add a link between the 2 addons
Cheers

**Comment by JoseFSilva** [comment]
Dear cxii-dev,

You just changed the way I watch content on Kodi thanks to this change. Quasar can now be my default content source for me, your feature has been working like a charm! Thank you very much, that was a great and fast "customer" support on your part :)

I think other users will find this enhancement quite useful as well.

**Comment by JoseFSilva** [comment]
Maybe I'll open an issue on Quasar repo for adding TVShow Time integration but development there seems to be slow.

**Comment by JoseFSilva** [comment]
Also, I'm a web developer but taking my first steps on python and the opensource dev world. Could anyone (me) outside your team contribute to this repo?

**Comment by cxii-dev** [comment]
Thank you Jose.
I added a few lines to bypass the links.
I've tried on some, maybe not all can be bypassed ...
Cheers

**Comment by JoseFSilva** [comment]
It's not a problem, there would be too many file name possibilities to cover them all anyway.
Thanks again, have a great day!

**Comment by JoseFSilva** [comment]
I just tried the 1.1.2 and it says episode not found for the ones that used to work :( I'm going back to 1.1.1 for now.
Maybe is better to rollback and forget about the links?

**Comment by cxii-dev** [comment]
Have you the name of the file?

**Comment by JoseFSilva** [comment]
I came back to 1.1.1 and is not working with any file, I think maybe I didn't install correctly?

I selected 'Download zip' and Kodi > Install from zip
or should I extract zip to addon folder?

**Comment by JoseFSilva** [comment]
Two of them:
https://rarbg.to/torrent/3lyjh49
https://rarbg.to/torrent/v3dkih5

**Comment by JoseFSilva** [comment]
Reopening until this is fixed.

**Comment by JoseFSilva** [comment]
Thank you again @cxii-dev.
Closing issue now that it's fixed 8f68049.

**Comment by JoseFSilva** [comment]
Thank you again @cxii-dev.
Closing issue now that it's fixed 8f68049.

**Comment by cxii-dev** [comment]
The new 1.1.2 is out and working ... 
Cheers
