### ISSUE TITLE
Compile bash

### ISSUE THREAD

**Issue by raspdealer** [cxii-dev/script.tvshowtime#6]
Can you please add the compile.sh file in the root folder ?
Thanks.

**Comment by cxii-dev** [comment]
Hi, could you help me with tis file ?

**Comment by raspdealer** [comment]
*Open nano 
sudo nano

*Paste this script (Copy first, Right click in putty window to paste)
#!/bin/bash
dest=script.tvshowtime
version=$(grep "^\s\+version" addon.xml | cut -f2 -d'"')

if [ -d $dest ]; then
    rm -r $dest
fi

mkdir $dest
cp addon.xml $dest/
cp *.txt $dest/
cp icon.png $dest/
cp *.py $dest/
cp -r resources $dest/

if [ -f $dest-$version.zip ]; then
    rm $dest-$version.zip
fi

zip -r $dest-$version.zip $dest
rm -r $dest

*Save the file
Make a Ctrl + X command to exit
Type the name "compile.sh" and Press Enter

Then Commit the file in your repo (To let people who wants to compile manually

**Comment by cxii-dev** [comment]
The same I have in the old readme.md ?

https://github.com/cxii-dev/script.tvshowtime/blob/b293bcb7ef18a4f2a782d99a71ac15f095df8515/README.md

**Comment by raspdealer** [comment]
Yes it works properly  !

**Comment by cxii-dev** [comment]
Ok, I will pull that
