### ISSUE TITLE
Submit to Kodi official repository

### ISSUE THREAD

**Issue by raspdealer** [cxii-dev/script.tvshowtime#7]
Hi, 
Can you submit your add-on on the official Kodi repository.
This way, we will not need to compile manually anymore and can get automatically the last version.

Please read : http://kodi.wiki/view/Submitting_Add-ons

Thanks.

**Comment by cxii-dev** [comment]
The addon is submitted ... 
http://addons.xbmc.org/show/script.tvshowtime/

**Comment by raspdealer** [comment]
On version 1.0.6...
But the last version is 1.0.10 righ ?

**Comment by cxii-dev** [comment]
Yes, I have pull the 1.0.10 last week, and still waiting
I'll wait till tomorow morning to pull the 1.0.11 if no bugs

**Comment by cxii-dev** [comment]
the 1.0.12 is submitted to kodi repo

**Comment by raspdealer** [comment]
How many time for the validation ?
