### ISSUE TITLE
Authentication method changed

### ISSUE THREAD

**Issue by tbitowt** [cxii-dev/script.tvshowtime#8]
Seems that TVShowTime changed authentication method.

I cannot get token from http://bit.ly/TVShowTime and my previous source, which were authenticated by username & pass don't work any more.

Seems that TVShowTime now using OAuth2 and API is described here:
https://api.tvshowtime.com/doc

**Comment by cxii-dev** [comment]
Hi, the 1.0.12 works since api changes
The http://bit.ly/TVShowTime works for me.
Do you have an error ?

**Comment by raspdealer** [comment]
application/x-www-form-urlencoded
OAuth client error

Error: OAuth server did not return the access token

**Comment by raspdealer** [comment]
OK a F5 is needed after error...

**Comment by cxii-dev** [comment]
Ok I will check

**Comment by tbitowt** [comment]
Yep, F5 helps.
